{"uuid": "5372d4d7-57e2-46a6-97e3-2d828942fd70", "children": ["6e8163db-517f-4949-8579-390d5c2c6400"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: No connection could be made because the target machine actively refused it. (os error 10061)\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\USER\\PycharmProjects\\store\\Test_case\\conftest.py\", line 5, in setup\n    driver=webdriver.Firefox()\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 184, in __init__\n    keep_alive=True)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 266, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1706421681775, "stop": 1706421815740}], "start": 1706421681775, "stop": 1706421816539}